version: '3'
services:
  branch:
    image: masterserver
    container_name: branchmaster
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./branchcfg:/etc/branch/" 
      - "./branchworkdirectory:/branchworkdirectory"
    ports:
      - "8080:8080"
      - "27015:27015"
