def helpMsg():
    print("Branch - The AcaciaLinux package build utility")
    print("---------------------------------")
    print("init:")
    print("Initialize a new package directory.")
    print()
    print("pack:")
    print("Creates a package from cwd")
    print()
    print("push:")
    print("Pushes a package to the repository server.")
    print()
    print("help:")
    print("Displays this help message")
    print()
    print("packpush:")
    print("Runs pack and push")
    print()
    print("reconf:")
    print("Deletes the current configuration file and reruns the setup assistant")
    print()
    print("build:")
    print("Builds a package from source")
    print()
    print("buildpack:")
    print("Runs build and pack")
    print()
    print("buildpackpush:")
    print("Runs build, pack and push")
    print()
    print("bpbutil:")
    print("Utility to easily create bpb files")
    print()
