version: '3'
services:
  buildbot:
    image: buildbot
    privileged: true
    container_name: branchbuildbot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./branchcfg:/etc/branch/" 
      - "./branchworkdirectory:/branchworkdirectory"
