def helpMsg():
    print("Branch - The AcaciaLinux packager")
    print("---------------------------------")
    print("init:")
    print("Initialize a new package directory.")
    print()
    print("pack:")
    print("Creates a package from cwd")
    print()
    print("push:")
    print("Pushes a package to the repository server.")
    print()
    print("help:")
    print("Displays this help message")
    print()
    print("packpush:")
    print("Runs pack and push")
    print()
    print("reconf:")
    print("Deletes the current configuration file and reruns the setup assistant")
