branchlog:
	@echo "Installing branchlog python package"
	cd branchlog && python3 setup.py sdist bdist_wheel && python3 -m pip install dist/branchlog-1.0-py3-none-any.whl --force-reinstall
	cd branchcommons && python3 setup.py sdist bdist_wheel && python3 -m pip install dist/branchcommons-1.0-py3-none-any.whl --force-reinstall
